using PixelCompanion;
var directory = Path.Combine(Path.GetTempPath(), "pixel-companion-check-" + Guid.NewGuid());
void Check(bool ok, string name) { if (!ok) throw new Exception(name); Console.WriteLine("PASS " + name); }
var pairing = new Pairing(directory);
string firstCode = pairing.Code;
Check(pairing.Pair("000000").Token == null, "invalid PIN");
var result = pairing.Pair(firstCode);
Check(result.Token?.Length == 64 && pairing.Valid(result.Token), "random token and validation");
Check(pairing.Pair(firstCode).Token == null, "single-use code");
Check(!File.ReadAllText(Path.Combine(directory,"devices.json")).Contains(result.Token!), "raw token not on server disk");
var restored = new Pairing(directory);
Check(restored.Valid(result.Token), "persistent token hash");
restored.Revoke(); Check(!restored.Valid(result.Token), "revoke");
for(int i=0;i<5;i++)restored.Pair("000000");
Check(restored.Pair(restored.Code).Token == null, "rate limit blocks brute force");
var limits = new Pairing(Path.Combine(directory,"limits"));
for(int i=0;i<8;i++)Check(limits.Pair(limits.Code).Token != null,"device " + i);
Check(limits.Pair(limits.Code).Token == null,"device limit");
var browser = new BrowserController();
var queue = new[] { new BrowserTrack("track-1", "First track", "Artist", true), new BrowserTrack("track-2", "Second track", "Artist", false) };
Check(browser.Update(queue, 0) == null && browser.Tracks.Length == 2, "browser queue update");
Check(!browser.Play("missing") && browser.Play("track-2"), "browser queue allowlist");
var browserCommand = browser.Update(queue, 0);
Check(browserCommand is { Name: "play-track", TrackId: "track-2" } && browser.Update(queue, browserCommand.Sequence) == null, "browser play command sequence");
File.Delete(Path.Combine(directory,"devices.json"));
File.Delete(Path.Combine(directory,"limits","devices.json"));
Directory.Delete(Path.Combine(directory,"limits"));
Directory.Delete(directory);
